name: Publish Python package to GitHub Packages
on:
  push:
    tags:
      - 'v*.*.*'   # dispara quando você empurra uma tag semântica

permissions:
  contents: read
  packages: write      # necessário para que o token consiga publicar

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish to GitHub Packages (usando secret AEB_TOKEN)
        env:
          TWINE_USERNAME: ${{ github.actor }}         # ou "ViniciusKanh"
          TWINE_PASSWORD: ${{ secrets.AEB_TOKEN }}    # seu secret AEB_TOKEN
        run: |
          python -m twine upload --repository-url "https://pypi.pkg.github.com/${{ github.repository_owner }}" dist/* --verbose
