name: Publish Python package to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'     # dispara quando você empurra uma tag semântica
  workflow_dispatch: {} # permite rodar manualmente pela UI

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to GitHub Packages (twine)
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.AEB_TOKEN }}
        run: |
          python -m twine upload --repository-url "https://pypi.pkg.github.com/${{ github.repository_owner }}" dist/* --verbose
